# Training configuration
GPU: [0]

VERBOSE: False

MODEL:
  MODE: 'LLFormer_ExDark'

# Optimization arguments.
OPTIM:
  BATCH: 16 # 8 originally
  EPOCHS: 4000
  # EPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 128
  VAL_PS: 128
  TRAIN_DIR: './datasets/ExDark/train/'      # path to training data
  VAL_DIR: './datasets/ExDark/val'
  SAVE_DIR: './datasets/ExDark/checkpoints' # path to save models and images

